################################################################################
# General behavior

set -g default-terminal "screen-256color"
#set -g default-shell /usr/bin/fish
#set -g default-shell /usr/bin/bash

set-option -g update-environment 'LS_COLORS XDG_VTNR XDG_SESSION_ID XDG_SEAT XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS GOPATH _JAVA_OPTIONS MAVEN_OPTS SAL_USE_VCLPLUGIN DISPLAY SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY'

set -g display-time 2000
set -g history-limit 100000
set -g display-panes-active-colour red

# Forward terminal focus events to inner apps (Neovim, Claude Code, etc.)
set -g focus-events on

################################################################################
# UI

set-window-option -g window-status-current-style bg=magenta #lightslateblue

################################################################################
# General key bindings

# Change default prefix key
#unbind C-b
#set -g prefix C-a
#bind C-a send-prefix

setw -g mode-keys vi

# Fix Shift+Enter, Ctrl+Enter, and Alt+Enter collapsing to plain Enter.
# Todo: check version, set `extended-keys` conditionally
#set -g extended-keys on
#set -g extended-keys-format csi-u

unbind '"'
unbind %

set-option -s escape-time 10

# Begin selection
unbind '['
bind Space copy-mode

# Copy selected into internal buffer
#bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel

# Paste selection
unbind ']'
#bind p run "xclip -o -sel clip | tmux load-buffer - ; tmux paste-buffer"
bind p paste-buffer

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi 'C-v' send-keys -X rectangle-toggle \; send-keys -X begin-selection

unbind 'h'
bind -Tcopy-mode-vi j send -X cursor-left
bind -Tcopy-mode-vi k send -X cursor-down
bind -Tcopy-mode-vi l send -X cursor-up
bind -Tcopy-mode-vi \; send -X cursor-right

# Kill pane without confirmation
bind x kill-pane

################################################################################
# Windows and panes

# Choose window
bind N swap-window -t -1\; select-window -t -1
bind P swap-window -t +1\; select-window -t +1
bind n previous-window
bind p next-window
#bind M-[ swap-window -t -1\; select-window -t -1
#bind M-] swap-window -t +1\; select-window -t +1
#bind [ previous-window
#bind ] next-window
#unbind n

set-option -g renumber-windows on

# Pane indexes
set -g base-index 1
setw -g pane-base-index 1

# Select panes
bind j select-pane -L
bind k select-pane -D
bind l select-pane -U
bind \; select-pane -R

# Split panes
bind s split-window -c "#{pane_current_path}" # Horizontal split with setting path to $(pwd)
bind v split-window -h -c "#{pane_current_path}" # Vertical split with setting path to $(pwd)
