include $(CURDIR)/../../prelude.mk
GNUMAKEFLAGS :=

################################################################################
# CI-CD

ci-cd-build:
	echo todo: $(CURDIR)

ci-cd-test:
	echo todo: $(CURDIR)

ci-cd-deploy:
	echo todo: $(CURDIR)

