" This file may be sourced from ~/.config/nvim/init.lua

" let s:this_file_dir_path=expand("<sfile>:p:h")
"fu! Include(script_path)
"    :exec ":source " . s:this_file_dir_path . "/" . a:script_path . ".vim"
"endf

fu! SetupPlugins()
    " netrw
    fu! OpenNetrw()
        " Open if no stdin and no args
        if !exists("s:std_in") && 0 == argc()
            execute 'Explore'
        end
    endf
    autocmd StdinReadPre * let s:std_in=1
    autocmd VimEnter * call OpenNetrw()
    let g:netrw_banner=0
    " See `:help netrw-c`
    let g:netrw_keepdir = 0

    " Allow to delete not empty directories
    let g:netrw_localrmdir='rm -rf'
    let g:netrw_sort_sequence=''
endf

fu! SetupBehavior()
    " https://vim.fandom.com/wiki/Have_Vim_check_automatically_if_the_file_has_changed_externally
    au FocusGained,BufEnter * :silent! !

    set nocompatible
"    set autochdir
    set backspace=indent,eol,start
    set confirm

    " Disable reading .editorconfig files
    let g:editorconfig = 0

    " Unfold by default
    set foldlevelstart=99
"    set foldmethod=indent

    set nobackup
    "set nowritebackup

    " Swap file related settings
    "  set noswapfile
    if !isdirectory($HOME."/.vim/swp")
        silent! execute "!mkdir ~/.vim/swp"
    endif
    set directory=$HOME/.vim/swp// " The trailing double slash is required

    " Sessions
    set sessionoptions+=unix,slash
    set ssop-=options    " do not store global and local values in a session
    set ssop-=folds      " do not store folds

    set showcmd
    set showmatch
    set ttyfast
    set wrap
    set textwidth=0

    " set autowriteall

    " Disable the history ~/.viminfo file.
    set viminfo=

    call SetupPlugins()

    " Don't auto append <EOL> 0x0a at the end of file
    set endofline

    " Tell the `:find` search recursively
    set path=**

    "runtime macros/matchit.vim

    fu! SetupAutoCommands()
        " https://stackoverflow.com/a/27387138/13393715
        "autocmd! TextChanged,TextChangedI <buffer> silent write

        fu! SetIndent(size)
            let &l:sw = a:size
            let &l:ts = a:size
            setlocal expandtab
        endf

        fu! YamlLikeIndent()
            let prev = getline(v:lnum - 1)
            let prev_indent = indent(v:lnum - 1)

            " Only indent deeper after a line ending with ':'
            if prev =~# ':\s*$'
                return prev_indent + &l:sw
            endif

            return prev_indent
        endf

        fu! SetLLVMBehavior()
            " https://github.com/llvm/llvm-project/blob/main/llvm/utils/vim/ftplugin/llvm.vim
            set filetype=llvm
            setlocal softtabstop=2 shiftwidth=2
            setlocal comments+=:;
        endf

        fu! SetTableGenBehaviour()
            " https://github.com/llvm/llvm-project/blob/main/llvm/utils/vim/ftplugin/tablegen.vim
            set filetype=tablegen
            setlocal matchpairs+=<:>
            setlocal softtabstop=2 shiftwidth=2
        endf

        fu! SetLispBehaviour()
            "au BufNewFile,BufRead *.scm call PareditInitBuffer()
            "    imap <c-h> <Plug>snipMateNextOrTrigger
            "    smap <c-h> <Plug>snipMateNextOrTrigger
            "let g:snips_trigger_key = '<C-Space>'

            "map <c-l> :call SlimvEvalExp()<cr>
            "imap <c-l> <c-o>:call SlimvEvalExp()<cr>

            set shiftwidth=4
            set tabstop=4
            let g:scheme_builtin_swank=1
            let g:slimv_impl = 'sbcl'
            let g:slimv_balloon=1
            let g:paredit_mode=0
            let g:paredit_electric_return=1
            let g:lisp_rainbow=0
        endf

        autocmd! BufNewFile,BufRead *.bt set filetype=unknown syntax=unknown shiftwidth=4
        autocmd! BufNewFile,BufRead *.g4 set filetype=antlr
        autocmd! BufNewFile,BufRead *.jsm setlocal ft=javascript
        "autocmd! BufNewFile,BufRead *.stg set filetype=stg
        autocmd! BufNewFile,BufRead *.wl,*.wls set filetype=wl
        autocmd! BufNewFile,BufRead *.pem set filetype=text

        " Default filetype
        "autocmd BufNewFile,BufRead * if &filetype == "" | setlocal ft=sh | endif
        "autocmd! BufWritePost .vimrc source %

        "Example of multiple commands: autocmd BufNewFile,BufRead *.l setlocal ft=l sw=4 ts=4 | setlocal spell | normal! G$a-- End of File --<Esc>
        "autocmd! BufNewFile,BufRead *.flex set filetype=lex
        "todo: setlocal vs set

        " Start in Insert mode.
        "autocmd! BufNewFile * startinsert
        "autocmd! VimEnter * if empty(expand("%")) | startinsert | endif

        " CMake
        autocmd! BufNewFile,BufRead CMakeLists.txt set filetype=cmake

        " GDB
        autocmd! BufNewFile,BufRead *.gdb set filetype=gdb

        " Go
        autocmd! BufNewFile,BufRead *.go set noet

        " Haskell
        autocmd! Filetype haskell set shiftwidth=4 tabstop=4
        autocmd! Filetype cabal set shiftwidth=4 tabstop=4

        " L (https://github.com/njcom/morpho/tree/main/module/l)
        autocmd! BufNewFile,BufRead *.l setlocal ft=l
        autocmd! Filetype l call SetIndent(2) | setlocal indentexpr=YamlLikeIndent()

        " LLVM
        autocmd! BufNewFile,BufRead *.td call SetTableGenBehaviour()
        autocmd! BufNewFile,BufRead *.ll call SetLLVMBehavior()

        " Lisp
        autocmd! BufNewFile,BufRead *.lisp set filetype=lisp
        autocmd! Filetype lisp call SetLispBehaviour()

        " Lua
        autocmd! BufNewFile,BufRead *.lua set filetype=lua ts=2 sw=2

        " Make
        autocmd! BufNewFile,BufRead Makefile,*.mk set noexpandtab

        " Markdown
        autocmd! BufNewFile,BufRead *.markdown,*.md,*.mdown,*.mkd,*.mkdn,*.txt setlocal filetype=markdown
        autocmd! Filetype markdown call SetIndent(2)

        " PHP
        autocmd! BufNewFile,BufRead *.php,*.module,*.inc,*.test,*.install,*.profile,*.phar set filetype=php autoindent
        autocmd! BufNewFile,BufRead *.phtml set filetype=phtml autoindent

        " Python
        autocmd! BufNewFile,BufRead *.py set indentexpr=

        " SML
        autocmd! Filetype sml set shiftwidth=4 tabstop=4

        " Scala
        autocmd! BufNewFile,BufRead *.sc set filetype=scala

        " Terraform
        autocmd! BufNewFile,BufRead *.tf,*.tfvars set sw=2 ts=2 filetype=terraform

        " TypeScript, JavaScript
        autocmd! BufNewFile,BufRead *.ts set filetype=typescript
        autocmd! BufNewFile,BufRead tsconfig.json set filetype=javascript

        " Vim
        autocmd! Filetype vim set shiftwidth=4 tabstop=4 textwidth=0

        autocmd! BufEnter * silent! lcd %:p:h
    endf

    fu! SetupCommands()
        " Fount at https://github.com/llvm/llvm-project/blob/main/llvm/utils/vim/vimrc
        " Delete trailing whitespace and tabs at the end of each line
        command! DeleteTrailingWs :%s/\s\+$//

        " Convert all tab characters to 4 spaces
        command! TabsToSpaces :%s/\t/    /g
    endf

    call SetupCommands()
    call SetupAutoCommands()

    " Open windows to right and bottom
    set splitbelow
    set splitright

    set timeout timeoutlen=500

    let g:ruby_path="/usr/bin/ruby"
endf

fu! SetupIndent()
    " Get current settings: set ai? si? cin? sr? sta? sw? ts? et? ci?
    set autoindent " ai
    set nosmartindent " si
    set nocindent " cin
    set shiftround " sr
    set smarttab " sta
    set shiftwidth=4 " sw
    set tabstop=4 " ts
    set expandtab " et
    set copyindent " ci
    " <$key> means indent, $key means don't indent
    "set indentkeys=!^F,<o>,<O>,0#,0},0],<:>,0-
endf

fu! SetupFileFormat()
    if &modifiable
        set ffs=unix
        set fileformat=unix
    endif
endf

fu! SetupEncoding()
    let termencoding=&encoding
    set encoding=utf-8
    setglobal fenc=utf-8
    set fencs=ucs-bom,utf-8,cp1251,cp866,koi8-r
endf

fu! SetupStatusLine()
    set wildmenu
    "set wildmode=list:longest
    set wildmode=longest:list,full
    set laststatus=2
endf

fu! SetupCommandLine()
    set cmdheight=1
endf

fu! SetupColors()
    syntax on
    set t_Co=256
    "colorscheme industry
    colorscheme desert
    "colorscheme tango-dark
    "colorscheme monochrome
    "colorscheme xoria256
endf

fu! SetupCtags()
    set tags=tags;/
endf

fu! SetupView()
    set mousehide
    set cursorline
    set number relativenumber
    set ruler
    set list listchars=tab:»»,trail:·
    ",precedes:↲

    " Colorschemes are here: ~/.vim/bundle/lightline/autoload/lightline/colorscheme/
"    let g:lightline = {
"        \ 'colorscheme': 'my',
"        \ }

    "highlight MyCursor guibg=lightgreen
    "set selection=exclusive
    "set guicursor=a:ver25-MyCursor,a:blinkon0
    " Не менять форму курсора при входе в Insert mode.
    set guicursor=
"    set guifont=Consolas\ 10
    "set guifont=Source\ Code\ Pro\ 9

    " Fix empty space at the bottom for XMonad and Gvim
"    set guiheadroom=0

    " Keep 5 lines visible at bottom/top
    set scrolloff=5
endf

fu! SetupSearch()
    set ignorecase
    set smartcase
    set incsearch
    set hlsearch

    " Show number of matches. On loop shows the `W`
    set shortmess-=S

    " Options for `grep` which will be called with for the :grep and :lgrep
    set grepprg=grep\ -rnIiP\ --exclude-dir={.bzr,CVS,.git,.hg,.svn}

    " Search selected text with * and # in Visual mode, taken from http://vim.wikia.com/wiki/Search_for_visually_selected_text
"    vnoremap <silent> * :<C-U>
"        \let old_reg=getreg('"')<Bar>let old_regtype=getregtype('"')<CR>
"        \gvy/<C-R><C-R>=substitute(
"        \escape(@", '/\.*$^~['), '\_s\+', '\\_s\\+', 'g')<CR><CR>
"        \gV:call setreg('"', old_reg, old_regtype)<CR>
"    vnoremap <silent> # :<C-U>
"        \let old_reg=getreg('"')<Bar>let old_regtype=getregtype('"')<CR>
"        \gvy?<C-R><C-R>=substitute(
"        \escape(@", '?\.*$^~['), '\_s\+', '\\_s\\+', 'g')<CR><CR>
"        \gV:call setreg('"', old_reg, old_regtype)<CR>
endf

" Zoom / Restore window.
function! s:ZoomToggle() abort
    if exists('t:zoomed') && t:zoomed
        execute t:zoom_winrestcmd
        let t:zoomed = 0
    else
        let t:zoom_winrestcmd = winrestcmd()
        resize
        vertical resize
        let t:zoomed = 1
    endif
endfunction

fu! SetupKeys()
    " :help map.txt
    " :help map-modes
    " :help key-codes

    " Zoom current window: Ctrl+w z
    command! ZoomToggle call s:ZoomToggle()
    nnoremap <silent> <C-w>z :ZoomToggle<CR>

    " Left: j
    noremap j <Left>
"    " Down: k
    noremap k gj
"    " Up: l
    noremap l gk
    " Right: ;
    noremap ; <Right>

    " Move line up
    inoremap <C-l> <Esc>:m+<CR>==gi
    inoremap <C-l> <Esc>:m-2<CR>==gi
    nnoremap <C-l> mz:m-2<CR>`z==
    vnoremap <C-l> :m'<-2<CR>gv=`>my`<mzgv`yo`z
    " Move line down
    nnoremap <C-k> mz:m+<CR>`z==
    vnoremap <C-k> :m'>+<CR>gv=`<my`>mzgv`yo`z
    "vnoremap J :m '>+1<CR>gv=gv
    "vnoremap K :m '<-2<CR>gv=gv

    " To left window
    noremap <C-w>j <C-w>h
    noremap <C-w><C-j> <C-w>h

    " To down window
    noremap <C-w>k <C-w>j
    noremap <C-w><C-k> <C-w>j

    " To up window
    noremap <C-w>l <C-w>k
    noremap <C-w><C-l> <C-w>k

    " To right window
    noremap <C-w>; <C-w>l
    noremap <C-w><C-semicolon> <C-w>l

    " Leader key: Space
    nnoremap <Space> <nop>
    let g:mapleader = "\<Space>"
    let g:maplocalleader = "\<Space>"
    map <Space> <leader>

    " Put line up: p
    noremap <leader>p :put<cr>
    " Put line down: P
    noremap <leader>P :put!<cr>

    " To begin of line: Ctrl+a
    inoremap <C-a> <C-o>I
    " To end of line: Ctrl+e
    inoremap <C-e> <C-o>A
    " Delete right char: Ctrl+d
    inoremap <C-d> <C-o>x


    " Find next char for `f` or `t`: '
    noremap ' ;

    " Changed version from http://stackoverflow.com/questions/916875/yank-file-name-path-of-current-buffer-in-vim
    if has("unix") || has("gui_gtk") || has("gui_gtk2") || has("gui_gnome")
        nnoremap <leader>c :let @+=expand("%:p")<CR>
    endif

    " Print full file path
    nnoremap <leader>C :echo expand("%:p")<CR>

    " Save session: Space s s
"    exec 'nnoremap <Leader>ss :mksession! ~/.vim/session/session.vim'
    "nnoremap <leader>q :mksession! ~/.vim/session/

    " Open file manager: Space .
    noremap <silent> <leader>. :e .<cr>
"    noremap <silent> <leader>. :Explore<CR>
"   " Split vertically and open file manager: Space v
    noremap <silent> <leader>v :vsplit .<cr>
"   " Split horizontally and open file manager: Space v
    noremap <silent> <leader>s :split .<cr>

"    noremap <silent> <leader>i I$key<Esc>

    " https://www.youtube.com/watch?v=Q5eDxR7bU2k
    " Don't loose the pasted text
    "vnoremap <leader>p "_dP

    "--------------------------------------------------------------------------

    " Unbind Ctrl-l for the file manager
    augroup netrw_maps
        autocmd!
        autocmd filetype netrw call BindNetrwKeys()
    augroup END
    function BindNetrwKeys()
        if hasmapto('<Plug>NetrwRefresh')
            unmap <buffer> <C-l>
        endif
        "todo: copy full path with <leader>c
        "nnoremap <buffer> <nowait> <leader>c :let @+=get(b:, 'current_dir', getcwd()). '/'. <SID>NetrwGetWord())<cr>
"        nnoremap <buffer> <C-l> :wincmd k<cr>
        "nnoremap <buffer> <s-down> :wincmd j<cr>
    endfunction

    " Disable search highlight: Esc.
    nnoremap <silent> <esc> :noh<cr><esc>

    " Delete previous word: C-Backspace
    "cnoremap  <C-w>
    "inoremap  <C-w>
    " Fix Backspace for `find ... | xargs vim`
    noremap! <C-?> <C-h>

    if has('terminal')
        tnoremap <C-w>j <C-w>h
        tnoremap <C-w>k <C-w>j
        tnoremap <C-w>l <C-w>k
        tnoremap <C-w>; <C-w>l
    endif

    "todo set langmap=ёйцукенгшщзхъфывапролджэячсмитьбюЁЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ;`qwertyuiop[]asdfghjkl\\;'zxcvbnm\\,.~QWERTYUIOP{}ASDFGHJKL:\\"ZXCVBNM<>
    "todo set keymap=russian-jcukenwin

    function! s:ToggleQF()
        if !empty(filter(getwininfo(), 'v:val.quickfix'))
            cclose
        elseif !empty(getqflist())
            copen
        endif
    endfunction
    nnoremap <C-q> <Cmd>call <SID>ToggleQF()<CR>
endf

fu! Main()
    call SetupBehavior()
    call SetupIndent()
    call SetupFileFormat()
    call SetupEncoding()
    call SetupStatusLine()
    call SetupCommandLine()
    call SetupColors()
    call SetupCtags()
    call SetupView()
    call SetupSearch()
    call SetupKeys()
endf

call Main()
