"set autochdir
autocmd! BufEnter * silent! lcd %:p:h

set expandtab
set shiftwidth=4
set tabstop=4
set incsearch
set ignorecase
set smartcase
set hlsearch
set autoindent
"colorscheme desert
colorscheme industry

if !isdirectory($HOME."/.vim/swp")
    silent! execute "!mkdir ~/.vim/swp"
endif
set directory=$HOME/.vim/swp// " The trailing double slash is required
