<nav class="navbar navbar-expand-lg navbar-dark" id="main-menu" aria-label="Main menu">
    <div class="container-fluid">
        <!--        <a class="navbar-brand" href="#">Morpho</a>-->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link" href="/">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/test">Tests</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">Cache</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="<?= $this->e($this->uriWithRedirectToSelf('/localhost/cache/clean-routes')) ?>">Rebuild routes</a></li>
                        <li><a class="dropdown-item" href="<?= $this->e($this->uriWithRedirectToSelf('/localhost/cache/clean-all')) ?>" title="Rebuilds routes as well">Clean global cache</a></li>
                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-primary" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<div class="nav-scroller bg--body shadow-sm" style="margin-top: 1px">
    <nav class="nav nav-underline" aria-label="Secondary navigation">
        <a class="nav-link active" href="#">
            Friends
            <span class="badge bg-light text-dark rounded-pill align-text-bottom">27</span>
        </a>
        <a class="nav-link" href="#">Explore</a>
        <a class="nav-link" href="#">Suggestions</a>
        <a class="nav-link" href="#">Link</a>
        <a class="nav-link" href="#">Link</a>
        <a class="nav-link" href="#">Link</a>
        <a class="nav-link" href="#">Link</a>
        <a class="nav-link" href="#">Link</a>
    </nav>
</div>