<?php declare(strict_types=1);
/**
 * This file is part of njcom/framework
 * It is distributed under the 'Apache License Version 2.0' license.
 * See the https://github.com/njcom/framework/blob/main/LICENSE for the full license text.
 */
// This file was generated by the bin/peg script.
namespace Morpho\Compiler\Frontend\Peg;

/**
 * https://github.com/python/cpython/blob/3.12/Lib/token.py
 */
enum TokenType: int {
    case Ampersand = 19;
    case AmpersandEqual = 41;
    case Async = 57;
    case At = 49;
    case AtEqual = 50;
    case Await = 56;
    case Circumflex = 32;
    case CircumflexEqual = 43;
    case Colon = 11;
    case ColonEqual = 53;
    case Comma = 12;
    case Comment = 64;
    case Dedent = 6;
    case Dot = 23;
    case DoubleSlash = 47;
    case DoubleSlashEqual = 48;
    case DoubleStar = 35;
    case DoubleStarEqual = 46;
    case Ellipsis = 52;
    case Encoding = 67;
    case EndMarker = 0;
    case Equal = 22;
    case EqualEqual = 27;
    case ErrorToken = 66;
    case Exclamation = 54;
    case FstringEnd = 63;
    case FstringMiddle = 62;
    case FStringStart = 61;
    case Greater = 21;
    case GreaterEqual = 30;
    case Indent = 5;
    case LeftBrace = 25;
    case LeftParen = 7;
    case LeftShift = 33;
    case LeftShiftEqual = 44;
    case LeftSquareBrace = 9;
    case Less = 20;
    case LessEqual = 29;
    case Minus = 15;
    case MinusEqual = 37;
    case NL = 65;
    case NTokens = 68;
    case Name = 1;
    case NewLine = 4;
    case NotEqual = 28;
    case NtOffset = 256;
    case Number = 2;
    case Op = 55;
    case Percent = 24;
    case PercentEqual = 40;
    case Plus = 14;
    case PlusEqual = 36;
    case RightArrow = 51;
    case RightBrace = 26;
    case RightParen = 8;
    case RightShift = 34;
    case RightShiftEqual = 45;
    case RightSquareBrace = 10;
    case Semicolon = 13;
    case Slash = 17;
    case SlashEqual = 39;
    case SoftKeyword = 60;
    case Star = 16;
    case StarEqual = 38;
    case String = 3;
    case Tilde = 31;
    case TypeComment = 59;
    case TypeIgnore = 58;
    case VertBar = 18;
    case VertBarEqual = 42;

    /**
     * EXACT_TOKEN_TYPES in Python
     */
    public static function exactTypes(): array {
        return [
            '!'   => self::Exclamation,
            '!='  => self::NotEqual,
            '%'   => self::Percent,
            '%='  => self::PercentEqual,
            '&'   => self::Ampersand,
            '&='  => self::AmpersandEqual,
            '('   => self::LeftParen,
            ')'   => self::RightParen,
            '*'   => self::Star,
            '**'  => self::DoubleStar,
            '**=' => self::DoubleStarEqual,
            '*='  => self::StarEqual,
            '+'   => self::Plus,
            '+='  => self::PlusEqual,
            ','   => self::Comma,
            '-'   => self::Minus,
            '-='  => self::MinusEqual,
            '->'  => self::RightArrow,
            '.'   => self::Dot,
            '...' => self::Ellipsis,
            '/'   => self::Slash,
            '//'  => self::DoubleSlash,
            '//=' => self::DoubleSlashEqual,
            '/='  => self::SlashEqual,
            ':'   => self::Colon,
            ':='  => self::ColonEqual,
            ';'   => self::Semicolon,
            '<'   => self::Less,
            '<<'  => self::LeftShift,
            '<<=' => self::LeftShiftEqual,
            '<='  => self::LessEqual,
            '='   => self::Equal,
            '=='  => self::EqualEqual,
            '>'   => self::Greater,
            '>='  => self::GreaterEqual,
            '>>'  => self::RightShift,
            '>>=' => self::RightShiftEqual,
            '@'   => self::At,
            '@='  => self::AtEqual,
            '['   => self::LeftSquareBrace,
            ']'   => self::RightSquareBrace,
            '^'   => self::Circumflex,
            '^='  => self::CircumflexEqual,
            '{'   => self::LeftBrace,
            '|'   => self::VertBar,
            '|='  => self::VertBarEqual,
            '}'   => self::RightBrace,
            '~'   => self::Tilde,
        ];
    }
}
