unexport _JAVA_OPTIONS

srcDirName := src
dstDirName := dst

ANTLR_JAR_FILE_PATH := /usr/share/java/antlr-*-complete.jar

srcDirPath := $(curDirPath)/$(srcDirName)
dstDirPath := $(curDirPath)/$(dstDirName)
binDirPath := $(curDirPath)/bin
testDirPath := $(curDirPath)/test
antlr := antlr4 -Dlanguage=$(targetLang) -visitor -Werror
javac := javac -classpath $(ANTLR_JAR_FILE_PATH) -sourcepath $(dstDirPath) -h $(dstDirPath) -s $(dstDirPath) -d $(dstDirPath)

inFilePath := $(testDirPath)/$(relTestFilePath)
startRule ?= program

lexerGrammar := $(grammar)Lexer
parserGrammar := $(grammar)Parser
lexerGrammarFilePath := $(srcDirPath)/$(lexerGrammar).g4

test-lexer: tokens
tokens: lexer
	echo Input file: $(inFilePath)
	cd $(dstDirPath) && grun $(grammar) tokens -Werror -tokens $(inFilePath)

valid-tokens:
	$(MAKE) tokens 2>/dev/null
invalid-tokens:
	$(MAKE) tokens 2>&1 >/dev/null

test: test-parser
test-parser: #parser
	$(binDirPath)/parser test-all

test-parser-gui: compile-parser
	cd $(dstDirPath) && grun $(grammar) $(startRule) -Werror -gui $(inFilePath)

ci-test:
	$(binDirPath)/parser setup
	$(MAKE) parser
	$(MAKE) test

antlr-lexer: $(srcDirPath)/$(grammar)Lexer.g4 $(wildcard $(srcDirPath)/*.$(targetExt))
	$(antlr) $(lexerGrammarFilePath) -o $(dstDirPath)
	cp $(dstDirPath)/$(lexerGrammar).tokens $(srcDirPath)

antlr-parser: antlr-lexer $(srcDirPath)/$(grammar)Parser.g4
	$(antlr) $(srcDirPath)/$(parserGrammar).g4 -o $(dstDirPath)

lexer: antlr-lexer
	cp $(srcDirPath)/*.$(targetExt) $(dstDirPath)
	$(javac) $(dstDirPath)/$(lexerGrammar).$(targetExt)
	$(binDirPath)/parser fix $(targetLang)

parser: lexer antlr-parser
	$(javac) $(dstDirPath)/*.$(targetExt)
	$(binDirPath)/parser fix $(targetLang)

clean:
	rm -fv $(curDirPath)/*.tokens $(srcDirPath)/*.tokens # Generated by Idea
	test $(dstDirPath) != $(srcDirPath) && rm -rfv $(dstDirPath)

init:
	composer require antlr/antlr4-php-runtime

.PHONY: test-lexer tokens valid-tokens invalid-tokens test test-parser test-parser-gui ci-test antlr-lexer antlr-parser lexer parser clean init
.SILENT:
