on:
  schedule:
    # At 02:00 every day
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        #operating-system: [ubuntu-20.04, ubuntu-18.04, windows-latest, macos-10.15]
        operating-system: [ubuntu-24.04]
        #php-versions: ['8.0', '8.1', 'latest']
        php-version: ['latest']
    name: ${{ matrix.operating-system }}, php-${{ matrix.php-version }}
    steps:
      - name: init/pull-source
        uses: actions/checkout@v4

      - name: init/install-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: 'zend.assertions=1'
          #extensions: mbstring, xdebug, pcov, intl, gd
          #ini-values: "post_max_size=256M, short_open_tag=On, date.timezone=UTC"

      - name: build/cron-daily
        run: |
          make ci-cd-cron-daily

      - name: 'deploy/push-cron-changes'
        run: |
          .github/workflows/push-changes.sh 'Updates from GitHub action ${{ github.action }} (#5)'

#      - name: Create a Pull Request
#uses: peter-evans/create-pull-request@v5