# Based on https://github.com/shivammathur/test-setup-php/blob/master/.github/workflows/main.yml
on:
  workflow_dispatch:
  push:
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        #operating-system: [ubuntu-20.04, ubuntu-18.04, windows-latest, macos-10.15]
        operating-system: [ubuntu-latest]
        #php-versions: ['8.0', '8.1', 'latest']
        php-version: ['latest']
    name: ${{ matrix.operating-system }}, php-${{ matrix.php-version }}
    steps:
      - name: build/pull-git-repo
        uses: actions/checkout@v4

      - name: build/install-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          #extensions: mbstring, xdebug, pcov, intl, gd
          #ini-values: "post_max_size=256M, short_open_tag=On, date.timezone=UTC"

#      - name: Testing PHP version
#        run: |
#          php -v
#          #php -r "if(strpos(phpversion(), '${{ matrix.php-version }}') === false) throw new Exception('Wrong PHP version Installed');"

      - name: build/main
        run: |
          make ci-cd-build

      - name: test
        run: |
          #touch 56914c9a23b80267cb66c41ab26c55e5-remove-me-after-tests-completed
          make ci-cd-test
          #rm -fv 56914c9a23b80267cb66c41ab26c55e5-remove-me-after-tests-completed
          #test ! -e 56914c9a23b80267cb66c41ab26c55e5-remove-me-after-tests-completed
      - name: deploy
        run: |
          make ci-cd-deploy

