on:
  #  schedule:
  #    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull sources'
        uses: actions/checkout@v2

      - name: 'Install PHP'
        uses: shivammathur/setup-php@v2
        with:
          #todo: php-version: 8.1
          php-version: 8.0

      - name: 'Pull meta'
        run: |
          php --version
          cat /etc/os-release
          composer install
          make pull-meta
          ls -alhR task

      - name: 'Push the changes'
        run: |
          .github/workflows/push-changes.sh task/pull-meta "Issue #7: Updated meta"