on:
  schedule:
    # At 06:00 on Thursday.
    - cron: '0 6 * * 4'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull sources'
        uses: actions/checkout@v2

      - name: 'Install PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: 'Pull meta'
        run: |
          composer install
          make pull-meta

      - name: 'Push the changes'
        run: |
          .github/workflows/push-changes.sh "Issue #7: Updated meta"
